/**:
  grasp_service:
    ros__parameters:
      joints_controller_name: panther_ur5e_joint_trajectory_controller
      joints_names:
        - ur5e_shoulder_pan_joint
        - ur5e_shoulder_lift_joint
        - ur5e_elbow_joint
        - ur5e_wrist_1_joint
        - ur5e_wrist_2_joint
        - ur5e_wrist_3_joint

      positions_to_place_list:
        - neutral_pos
        - place_pos

      positions_to_place:
        neutral_pos:
          positions: [0.8, -2.8, 1.8, -1.76, 4.77, 0.0]
          time_to_target: 4
        home_pos:
          positions: [0.0, -3.4, 2.8, -1.57, 3.14, 0.0]
          time_to_target: 4
        place_pos:
          positions: [1.57, 0.04, 0.62, -2.26, 4.77, 0.0]
          time_to_target: 4


      positions_to_pick_list:
        - above_pos
        - pick_pos


      positions_to_pick:
        home_pos:
          positions: [0.0, -3.4, 2.8, -1.57, 3.14, 0.0]
          time_to_target: 2
        above_pos:
          positions: [0.0, -1.2, 0.89, -1.76, 4.77, 0.0]
          time_to_target: 2
        pick_pos:
          positions: [0.0, -0.88, 0.89, -1.76, 4.77, 0.0]
          time_to_target: 1


      positions_to_home_list:
        - neutral_pos
        - home_pos


      positions_to_home:
        home_pos:
          positions: [0.0, -3.4, 2.8, -1.57, 3.14, 0.0]
          time_to_target: 2
        neutral_pos:
          positions: [0.8, -2.8, 1.8, -1.76, 4.77, 0.0]
          time_to_target: 2

      time_to_wait_on_target: 1

      gripper_controller_name: panther_ur5e_robotiq_gripper_controller
      gripper_close: 0.5525
      gripper_open: 0.005
